/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdhkarRouteImport } from './routes/adhkar'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as QiblaRouteImport } from './routes/qibla'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TodayRouteImport } from './routes/today'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as CategoryIdRouteImport } from './routes/category.$id'
import { Route as DhikrIdRouteImport } from './routes/dhikr.$id'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryShelfRouteImport } from './routes/library.$shelf'
import { Route as QuranIndexRouteImport } from './routes/quran.index'
import { Route as QuranNRouteImport } from './routes/quran.$n'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdhkarRoute = AdhkarRouteImport.update({
  id: '/adhkar',
  path: '/adhkar',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const QiblaRoute = QiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIdRoute = CategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DhikrIdRoute = DhikrIdRouteImport.update({
  id: '/dhikr/$id',
  path: '/dhikr/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryShelfRoute = LibraryShelfRouteImport.update({
  id: '/$shelf',
  path: '/$shelf',
  getParentRoute: () => LibraryRoute,
} as any)
const QuranIndexRoute = QuranIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuranRoute,
} as any)
const QuranNRoute = QuranNRouteImport.update({
  id: '/$n',
  path: '/$n',
  getParentRoute: () => QuranRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adhkar': typeof AdhkarRoute
  '/custom': typeof CustomRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRouteWithChildren
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/book/$id': typeof BookIdRoute
  '/category/$id': typeof CategoryIdRoute
  '/dhikr/$id': typeof DhikrIdRoute
  '/library/$shelf': typeof LibraryShelfRoute
  '/quran/$n': typeof QuranNRoute
  '/library/': typeof LibraryIndexRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adhkar': typeof AdhkarRoute
  '/custom': typeof CustomRoute
  '/favorites': typeof FavoritesRoute
  '/qibla': typeof QiblaRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/book/$id': typeof BookIdRoute
  '/category/$id': typeof CategoryIdRoute
  '/dhikr/$id': typeof DhikrIdRoute
  '/library/$shelf': typeof LibraryShelfRoute
  '/quran/$n': typeof QuranNRoute
  '/library': typeof LibraryIndexRoute
  '/quran': typeof QuranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adhkar': typeof AdhkarRoute
  '/custom': typeof CustomRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRouteWithChildren
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/book/$id': typeof BookIdRoute
  '/category/$id': typeof CategoryIdRoute
  '/dhikr/$id': typeof DhikrIdRoute
  '/library/$shelf': typeof LibraryShelfRoute
  '/quran/$n': typeof QuranNRoute
  '/library/': typeof LibraryIndexRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adhkar'
    | '/custom'
    | '/favorites'
    | '/library'
    | '/qibla'
    | '/quran'
    | '/search'
    | '/settings'
    | '/today'
    | '/book/$id'
    | '/category/$id'
    | '/dhikr/$id'
    | '/library/$shelf'
    | '/quran/$n'
    | '/library/'
    | '/quran/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adhkar'
    | '/custom'
    | '/favorites'
    | '/qibla'
    | '/search'
    | '/settings'
    | '/today'
    | '/book/$id'
    | '/category/$id'
    | '/dhikr/$id'
    | '/library/$shelf'
    | '/quran/$n'
    | '/library'
    | '/quran'
  id:
    | '__root__'
    | '/'
    | '/adhkar'
    | '/custom'
    | '/favorites'
    | '/library'
    | '/qibla'
    | '/quran'
    | '/search'
    | '/settings'
    | '/today'
    | '/book/$id'
    | '/category/$id'
    | '/dhikr/$id'
    | '/library/$shelf'
    | '/quran/$n'
    | '/library/'
    | '/quran/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdhkarRoute: typeof AdhkarRoute
  CustomRoute: typeof CustomRoute
  FavoritesRoute: typeof FavoritesRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  QiblaRoute: typeof QiblaRoute
  QuranRoute: typeof QuranRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TodayRoute: typeof TodayRoute
  BookIdRoute: typeof BookIdRoute
  CategoryIdRoute: typeof CategoryIdRoute
  DhikrIdRoute: typeof DhikrIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adhkar': {
      id: '/adhkar'
      path: '/adhkar'
      fullPath: '/adhkar'
      preLoaderRoute: typeof AdhkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qibla': {
      id: '/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof QiblaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$id': {
      id: '/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof CategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dhikr/$id': {
      id: '/dhikr/$id'
      path: '/dhikr/$id'
      fullPath: '/dhikr/$id'
      preLoaderRoute: typeof DhikrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/$shelf': {
      id: '/library/$shelf'
      path: '/$shelf'
      fullPath: '/library/$shelf'
      preLoaderRoute: typeof LibraryShelfRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/quran/': {
      id: '/quran/'
      path: '/'
      fullPath: '/quran/'
      preLoaderRoute: typeof QuranIndexRouteImport
      parentRoute: typeof QuranRoute
    }
    '/quran/$n': {
      id: '/quran/$n'
      path: '/$n'
      fullPath: '/quran/$n'
      preLoaderRoute: typeof QuranNRouteImport
      parentRoute: typeof QuranRoute
    }
  }
}

interface LibraryRouteChildren {
  LibraryShelfRoute: typeof LibraryShelfRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryShelfRoute: LibraryShelfRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

interface QuranRouteChildren {
  QuranNRoute: typeof QuranNRoute
  QuranIndexRoute: typeof QuranIndexRoute
}

const QuranRouteChildren: QuranRouteChildren = {
  QuranNRoute: QuranNRoute,
  QuranIndexRoute: QuranIndexRoute,
}

const QuranRouteWithChildren = QuranRoute._addFileChildren(QuranRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdhkarRoute: AdhkarRoute,
  CustomRoute: CustomRoute,
  FavoritesRoute: FavoritesRoute,
  LibraryRoute: LibraryRouteWithChildren,
  QiblaRoute: QiblaRoute,
  QuranRoute: QuranRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TodayRoute: TodayRoute,
  BookIdRoute: BookIdRoute,
  CategoryIdRoute: CategoryIdRoute,
  DhikrIdRoute: DhikrIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
